package com.example.demo.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;

import java.util.Date;

public class JwtUtil {

    private final byte[] secret;
    private final Long expirationMs;

    /**
     * REQUIRED constructor
     * Tests directly construct JwtUtil using a byte[] secret and expiration value
     */
    public JwtUtil(byte[] secret, Long expirationMs) {
        this.secret = secret;
        this.expirationMs = expirationMs;
    }

    /**
     * Generates JWT containing userId, email, and role
     */
    public String generateToken(Long userId, String email, String role) {

        return Jwts.builder()
                .setSubject(email)                // email stored as subject
                .claim("userId", userId)          // custom claim
                .claim("role", role)              // custom claim
                .setIssuedAt(new Date())
                .setExpiration(
                        new Date(System.currentTimeMillis() + expirationMs)
                )
                .signWith(SignatureAlgorithm.HS256, secret)
                .compact();
    }

    /**
     * Extract email (subject) from token
     */
    public String extractEmail(String token) {
        return extractAllClaims(token).getSubject();
    }

    /**
     * Extract role from token claims
     */
    public String extractRole(String token) {
        return extractAllClaims(token).get("role", String.class);
    }

    /**
     * Extract userId from token claims
     */
    public Long extractUserId(String token) {
        return extractAllClaims(token).get("userId", Long.class);
    }

    /**
     * Validate token
     * - Returns true for valid tokens generated by generateToken
     * - Returns false for invalid / random strings
     */
    public boolean validateToken(String token) {
        try {
            extractAllClaims(token);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    /**
     * Internal helper method to parse claims
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parser()
                .setSigningKey(secret)
                .parseClaimsJws(token)
                .getBody();
    }
}
